# Generated by Django 4.1.7 on 2023-03-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='deskription',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
